version: '3'

services:
  invoice-service:
    build: invoice_service
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - ../files:/app/shared
    environment:
      - PORT=5000
      - LOG_LEVEL=INFO
      - DEFAULT_OCR_ENGINE=auto
      - TESSERACT_LANG=chi_sim+eng+chi_tra
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MODEL_NAME=gpt-4
    env_file:
      - .env
    restart: unless-stopped
    container_name: invoice-service
    
  # 如果想同时运行n8n，可以取消下面的注释
  # n8n:
  #   image: n8nio/n8n
  #   ports:
  #     - "5678:5678"
  #   volumes:
  #     - ~/.n8n:/home/node/.n8n
  #     - ../files:/files
  #   environment:
  #     - N8N_BASIC_AUTH_ACTIVE=true
  #     - N8N_BASIC_AUTH_USER=admin
  #     - N8N_BASIC_AUTH_PASSWORD=password
  #   depends_on:
  #     - invoice-service
  #   restart: unless-stopped 